backend/crm/urls.py
from django.urls import include, path

from backend.crm import views as v

app_name = 'crm'


cliente_urlpatterns = [
    path('', v.ClienteListView.as_view(), name='cliente_list'),  # noqa E501
    path('detail/<int:pk>/', v.ClienteDetailView.as_view(), name='cliente_detail'),  # noqa E501
    path('create/', v.ClienteCreateView.as_view(), name='cliente_create'),  # noqa E501
]


fornecedor_urlpatterns = [
    path('', v.FornecedorListView.as_view(), name='fornecedor_list'),  # noqa E501
    path('detail/<int:pk>/', v.FornecedorDetailView.as_view(), name='fornecedor_detail'),  # noqa E501
    path('create/', v.FornecedorCreateView.as_view(), name='fornecedor_create'),  # noqa E501
]


urlpatterns = [
    path('cliente/', include(cliente_urlpatterns)),
    path('fornecedor/', include(fornecedor_urlpatterns)),
]

backend/orcamento/urls.py
from django.urls import include, path

from backend.orcamento import views as v

app_name = 'orcamento'


orcamento_patterns = [
    path('', v.OrcamentoListView.as_view(), name='orcamento_list'),  # noqa E501
    path('detail/<int:pk>/', v.OrcamentoDetailView.as_view(), name='orcamento_detail'),  # noqa E501
    path('create/<int:client_pk>/', v.orcamento_create, name='orcamento_create'),  # noqa E501
    path('update/<int:pk>/', v.orcamento_update, name='orcamento_update'),  # noqa E501
    path('produto/preco/', v.produto_preco, name='produto_preco'),  # noqa E501
    path('search/', v.produto_items_search, name='produto_items_search'),  # noqa E501
    path('add-row/', v.add_row_orcamento_items_hx, name='add_row_orcamento_items_hx'),  # noqa E501
    path('invoice/<int:pk>/', v.orcamento_invoice, name='orcamento_invoice'),  # noqa E501
]

contrato_patterns = [
    path('create/<int:orcamento_pk>/', v.contrato_create, name='contrato_create'),  # noqa E501
    path('<int:pk>/', v.ContratoDetailView.as_view(), name='contrato_detail'),  # noqa E501
]

urlpatterns = [
    path('orcamento/', include(orcamento_patterns)),
    path('contrato/', include(contrato_patterns)),
]

backend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('backend.core.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('crm/', include('backend.crm.urls', namespace='crm')),
    path('produto/', include('backend.produto.urls', namespace='produto')),
    path('orcamento/', include('backend.orcamento.urls', namespace='orcamento')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/crm/models.py
from django.db import models
from django.urls import reverse

from backend.core.models import (
    Active,
    Address,
    CreatedBy,
    DeletedBy,
    TimeStampedModel
)


class Cliente(TimeStampedModel, Address, CreatedBy, DeletedBy, Active):
    CNPJ = 'CNPJ'
    CPF = 'CPF'

    TIPO_REGISTRO = [
        (CNPJ, CNPJ),
        (CPF, CPF),
    ]

    tipo = models.CharField(max_length=4, choices=TIPO_REGISTRO, default=CNPJ)
    rg = models.CharField('RG', max_length=20, null=True, blank=True)
    cpf = models.CharField('CPF', max_length=11, null=True, blank=True)
    cnpj = models.CharField('CNPJ', max_length=14, null=True, blank=True)
    nome = models.CharField('Nome Completo', max_length=250)
    razao_social = models.CharField('Razão Social', max_length=250, null=True, blank=True)  # noqa E501
    nome_fantasia = models.CharField('Nome Fantasia', max_length=250, null=True, blank=True)  # noqa E501
    endereco_entrega = models.CharField('Endereço Entrega', max_length=250, null=True, blank=True)  # noqa E501

    def is_upperclass(self):
        return self.tipo in {self.CNPJ, self.CPF}

    class Meta:
        ordering = ('nome',)
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'

    @property
    def codigo(self):
        return str(self.pk).zfill(3)

    def __str__(self):
        return f'{self.nome}'

    def get_absolute_url(self):
        return reverse('crm:cliente_detail', kwargs={'pk': self.pk})


class Fornecedor(TimeStampedModel, Address, CreatedBy, DeletedBy, Active):
    CNPJ = 'CNPJ'
    CPF = 'CPF'

    TIPO_REGISTRO = [
        (CNPJ, CNPJ),
        (CPF, CPF),
    ]

    tipo = models.CharField(max_length=4, choices=TIPO_REGISTRO, default=CNPJ)
    rg = models.CharField('RG', max_length=20, null=True, blank=True)
    cpf = models.CharField('CPF', max_length=11, null=True, blank=True)
    cnpj = models.CharField('CNPJ', max_length=14, null=True, blank=True)
    nome = models.CharField('Nome Completo', max_length=250)
    razao_social = models.CharField('Razão Social', max_length=250, null=True, blank=True)  # noqa E501
    nome_fantasia = models.CharField('Nome Fantasia', max_length=250, null=True, blank=True)  # noqa E501
    endereco_entrega = models.CharField('Endereço Entrega', max_length=250, null=True, blank=True)  # noqa E501
    condicao_pagamento = models.PositiveIntegerField('Prazo de pagamento', null=True, blank=True)  # noqa E501

    class Meta:
        ordering = ('nome',)
        verbose_name = 'Fornecedor'
        verbose_name_plural = 'Fornecedores'

    @property
    def codigo(self):
        return str(self.pk).zfill(3)

    def __str__(self):
        return f'{self.nome}'

    def get_absolute_url(self):
        return reverse('crm:fornecedor_detail', kwargs={'pk': self.pk})

backend/crm/forms.py
from django import forms

from .models import Cliente, Fornecedor


class ClienteForm(forms.ModelForm):
    required_css_class = 'required'

    class Meta:
        model = Cliente
        fields = (
            'tipo',
            'cnpj',
            'rg',
            'cpf',
            'nome',
            'razao_social',
            'nome_fantasia',
            'address',
            'address_number',
            'complement',
            'district',
            'city',
            'uf',
            'cep',
            'endereco_entrega',
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field = self.fields.get(field_name)
            field.widget.attrs.update({'placeholder': field.label})
            field.widget.attrs['class'] = 'form-control'

        self.fields['tipo'].widget.attrs['onchange'] = "getElement(this.value,'element')"


class FornecedorForm(forms.ModelForm):
    required_css_class = 'required'

    class Meta:
        model = Fornecedor
        fields = (
            'tipo',
            'cnpj',
            'rg',
            'cpf',
            'nome',
            'razao_social',
            'nome_fantasia',
            'address',
            'address_number',
            'complement',
            'district',
            'city',
            'uf',
            'cep',
            'endereco_entrega',
            'condicao_pagamento',
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field = self.fields.get(field_name)
            field.widget.attrs.update({'placeholder': field.label})
            field.widget.attrs['class'] = 'form-control'

        self.fields['tipo'].widget.attrs['onchange'] = "getElement(this.value,'element')"

backend/cliente/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from .forms import ClienteForm
from .models import Cliente


@login_required
def cliente_list(request):
    template_name = 'cliente_list.html'
    objects = Cliente.objects.all()
    context = {
        'object_list': objects,
    }
    return render(request, template_name, context)


@login_required
def cliente_create(request):
    template_name = 'cliente_form_add_v2.html'
    clienteForm = ClienteForm
    context = {
        'form': clienteForm,
    }
    return render(request, template_name, context)

backend/crm/views.py
from django.contrib.auth.mixins import LoginRequiredMixin as LRM
from django.views.generic import CreateView, DetailView, ListView, UpdateView

from .forms import ClienteForm, FornecedorForm
from .models import Cliente, Fornecedor


class ClienteListView(LRM, ListView):
    model = Cliente


class ClienteDetailView(LRM, DetailView):
    model = Cliente


class ClienteCreateView(LRM, CreateView):
    model = Cliente
    form_class = ClienteForm


class FornecedorListView(LRM, ListView):
    model = Fornecedor


class FornecedorDetailView(LRM, DetailView):
    model = Fornecedor


class FornecedorCreateView(LRM, CreateView):
    model = Fornecedor
    form_class = FornecedorForm

backend/crm/templates/crm/cliente_detail.html
{% extends 'base.html'%}
{% load static %}

{% block content %}
  <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <h2>
      {{ object }}
      <a href="{% url 'crm:cliente_list' %}">
        <button type="button" class="btn btn-link">
          <span class="fw-semibold">Voltar</span>
        </button>
      </a>
    </h2>
    <div>

      <div class="mt-4">
        <p class="text-muted mb-1">Tipo:</p>
        <h5 class="font-size-14">{{ object.tipo }}</h5>
      </div>

      <div class="mt-4">
        {% if object.tipo == 'CPF' %}
          <p class="text-muted mb-1">CPF:</p>
          <h5 class="font-size-14">{{ object.cpf }}</h5>
        {% else %}
          <p class="text-muted mb-1">CNPJ:</p>
          <h5 class="font-size-14">{{ object.cnpj }}</h5>
        {% endif %}
      </div>

      <div class="mt-4">
        <p class="text-muted mb-1">RG:</p>
        <h5 class="font-size-14">{{ object.rg }}</h5>
      </div>

      <div class="mt-4">
        <p class="text-muted mb-1">Nome Completo:</p>
        <h5 class="font-size-14">{{ object.nome }}</h5>
      </div>

      <div class="mt-4">
        <p class="text-muted mb-1">Razão Social:</p>
        <h5 class="font-size-14">{{ object.razao_social }}</h5>
      </div>

      <div class="mt-4">
        <p class="text-muted mb-1">Nome Fantasia:</p>
        <h5 class="font-size-14">{{ object.nome_fantasia }}</h5>
      </div>

      <div class="mt-4">
        <p class="text-muted mb-1">Endereço:</p>
        <h5 class="font-size-14">{{ object.address }}, {{ object.address_number }}</h5>
      </div>

      <div class="mt-4">
        <p class="text-muted mb-1">Complemento:</p>
        <h5 class="font-size-14">{{ object.complement }}</h5>
      </div>

      <div class="mt-4">
        <p class="text-muted mb-1">Bairro:</p>
        <h5 class="font-size-14">{{ object.district }}</h5>
      </div>

      <div class="mt-4">
        <p class="text-muted mb-1">Cidade:</p>
        <h5 class="font-size-14">{{ object.city }}</h5>
      </div>

      <div class="mt-4">
        <p class="text-muted mb-1">UF:</p>
        <h5 class="font-size-14">{{ object.uf }}</h5>
      </div>

      <div class="mt-4">
        <p class="text-muted mb-1">CEP:</p>
        <h5 class="font-size-14">{{ object.cep }}</h5>
      </div>

      <div class="mt-4">
        <p class="text-muted mb-1">Endereco de Entrega:</p>
        <h5 class="font-size-14">{{ object.endereco_entrega }}</h5>
      </div>

    </div>
  </main>
{% endblock content %}

backend/crm/templates/crm/cliente_form.html
{% extends 'base.html'%}
{% load static %}
{% load widget_tweaks %}

{% block content %}
  <form action="." method="POST">
    {% csrf_token %}

    <div class="form-row">
      <div class="row">

        {% for field in form.visible_fields %}
          <div class="form-group col-sm-3">
            <label>{{ field.label }}</label>
            {% render_field field class="form-control" %}
            {% for error in field.errors %}
              <span class="text-muted">{{ error }}</span>
            {% endfor %}
          </div>
        {% endfor %}

      </div>
      <div class="row">
        <button class='btn btn-primary mt-3' type="submit">Salvar</button>
      </div>
    </div>

  </form>
{% endblock content %}

{% block js %}
  <script src="{% static 'js/script.js' %}"></script>
{% endblock js %}

backend/crm/templates/crm/cliente_list.html
{% extends 'base.html'%}
{% load static %}

{% block content %}
  <div class="card">
    <div class="d-flex bd-highlight">
      <div class="card-body">


        <h4 class="card-title mb-3">
          Clientes
          <a href="{% url 'crm:cliente_create' %}">
            <button type="button" class="btn btn-link shadow-none">
              Cadastrar
            </button>
          </a>
          <div class="dropdown d-inline">
            <a class="dropdown-toggle text-muted me-3 mb-3 align-middle" href="#" data-bs-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              <button type="button" class="btn btn-link shadow-none">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                  stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                  class="feather feather-search icon-sm">
                  <circle cx="11" cy="11" r="8"></circle>
                  <line x1="21" y1="21" x2="16.65" y2="16.65"></line>
                </svg><span>Buscar</span>
              </button></a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-end p-0">
              <form class="p-2">
                <div class="search-box">
                  <div class="position-relative">
                    <input type="text" class="form-control rounded bg-light border-0" placeholder="Buscar...">
                    <i class="font-size-16 search-icon"></i>

                  </div>
                </div>
              </form>
            </div>

          </div>
        </h4>

        <div class="table-responsive">
          <table class="table table-hover mb-0 align-middle">
            <thead class="bg-light">
              <tr>
                <th class="rounded-start" style="width: 15px;">
                  <div class="form-check">
                    <input class="form-check-input font-size-16" type="checkbox" value="" id="flexCheckDefault">
                    <label class="form-check-label" for="flexCheckDefault"> </label>
                  </div>
                </th>
                <th>Código</th>
                <th>Nome</th>
                <th>Razão Social</th>
                <th>Nome Fantasia</th>
                <th>Endereço</th>
                <th>Bairro</th>
                <th>Cidade</th>
                <th>Estado</th>
                <th>Ativo</th>
                <th></th>
              </tr>
              <!-- end tr -->
            </thead>
            <!-- end thead -->
            <tbody>
              {% for object in object_list %}
                <tr>
                  <td>
                    <div class="form-check">
                      <input class="form-check-input font-size-16" type="checkbox" value="" id="flexCheckexampleone">
                      <label class="form-check-label" for="flexCheckexampleone">
                      </label>
                    </div>
                  </td>
                  <td class="fw-medium">
                    {{ object.codigo }}
                  </td>
                  <td>
                    <a href="{{ object.get_absolute_url }}">{{ object.nome }}</a>
                  </td>
                  <td>
                    <div class="d-flex align-items-center">
                      <!-- Imagem do produto -->
                      <!-- <div class="me-2">
                          <img src="assets/images/users/avatar-2.jpg" class="avatar-sm img-thumbnail h-auto rounded-circle" alt="Error">
                      </div> -->
                      <div>
                        <h5 class="font-size-14 text-truncate mb-0">{{ object.razao_social }}
                        </h5>
                      </div>
                    </div>
                  </td>
                  <td>
                    {{ object.nome_fantasia }}
                  </td>

                  <td>
                    {{ object.address }}
                  </td>
                  <td>
                    {{ object.district }}
                  </td>
                  <td>
                    {{ object.city }}
                  </td>
                  <td>
                    {{ object.uf }}
                  </td>
                  <td style="min-width: 200px">
                    <div class="d-flex">
                      <div>
                        {% if object.active %}
                          <i class="mdi mdi-check-circle-outline text-success me-2"></i>
                          <a href="{% url 'orcamento:orcamento_create' object.pk %}">
                            <button type="button" class="btn btn-outline-success">Gerar Orçamento</button>
                          </a>
                        {% else %}
                          <i class="mdi mdi-close-circle-outline text-danger"></i>
                        {% endif %}
                      </div>
                    </div>
                  </td>
                  <td style="min-width: 70px">
                    <span>
                      <a href="#"><i class="mdi mdi-pencil text-success me-1"></i></a>
                    </span>
                    <span>
                      <a href="#"><i class="mdi mdi-trash-can text-danger me-1"></i></a>
                    </span>
                  </td>
                </tr>
              {% endfor %}
              <!-- end /tr -->
            </tbody><!-- end tbody -->
          </table><!-- end table -->
        </div>
      </div>
    </div>
{% endblock content %}

backend/crm/templates/crm/fornecedor_detail.html
{% extends 'base.html'%}
{% load static %}

{% block content %}
  <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <h2>
      {{ object }}
      <a href="{% url 'crm:fornecedor_list' %}">
        <button type="button" class="btn btn-link">
          <span class="fw-semibold">Voltar</span>
        </button>
      </a>
    </h2>
    <div>

      <div class="mt-4">
        <p class="text-muted mb-1">Tipo:</p>
        <h5 class="font-size-14">{{ object.tipo }}</h5>
      </div>

      <div class="mt-4">
        {% if object.tipo == 'CPF' %}
          <p class="text-muted mb-1">CPF:</p>
          <h5 class="font-size-14">{{ object.cpf }}</h5>
        {% else %}
          <p class="text-muted mb-1">CNPJ:</p>
          <h5 class="font-size-14">{{ object.cnpj }}</h5>
        {% endif %}
      </div>

      <div class="mt-4">
        <p class="text-muted mb-1">RG:</p>
        <h5 class="font-size-14">{{ object.rg }}</h5>
      </div>

      <div class="mt-4">
        <p class="text-muted mb-1">Nome Completo:</p>
        <h5 class="font-size-14">{{ object.nome }}</h5>
      </div>

      <div class="mt-4">
        <p class="text-muted mb-1">Razão Social:</p>
        <h5 class="font-size-14">{{ object.razao_social }}</h5>
      </div>

      <div class="mt-4">
        <p class="text-muted mb-1">Nome Fantasia:</p>
        <h5 class="font-size-14">{{ object.nome_fantasia }}</h5>
      </div>

      <div class="mt-4">
        <p class="text-muted mb-1">Endereço:</p>
        <h5 class="font-size-14">{{ object.address }}, {{ object.address_number }}</h5>
      </div>

      <div class="mt-4">
        <p class="text-muted mb-1">Complemento:</p>
        <h5 class="font-size-14">{{ object.complement }}</h5>
      </div>

      <div class="mt-4">
        <p class="text-muted mb-1">Bairro:</p>
        <h5 class="font-size-14">{{ object.district }}</h5>
      </div>

      <div class="mt-4">
        <p class="text-muted mb-1">Cidade:</p>
        <h5 class="font-size-14">{{ object.city }}</h5>
      </div>

      <div class="mt-4">
        <p class="text-muted mb-1">UF:</p>
        <h5 class="font-size-14">{{ object.uf }}</h5>
      </div>

      <div class="mt-4">
        <p class="text-muted mb-1">CEP:</p>
        <h5 class="font-size-14">{{ object.cep }}</h5>
      </div>

      <div class="mt-4">
        <p class="text-muted mb-1">Endereco de Entrega:</p>
        <h5 class="font-size-14">{{ object.endereco_entrega }}</h5>
      </div>

      <div class="mt-4">
        <p class="text-muted mb-1">Condição de Pagamento:</p>
        <h5 class="font-size-14">{{ object.condicao_pagamento }}</h5>
      </div>

    </div>
  </main>
{% endblock content %}

backend/crm/templates/crm/fornecedor_form.html
{% extends 'base.html'%}
{% load static %}
{% load widget_tweaks %}

{% block content %}
  <form action="." method="POST">
    {% csrf_token %}

    <div class="form-row">
      <div class="row">

        {% for field in form.visible_fields %}
          <div class="form-group col-sm-3">
            <label>{{ field.label }}</label>
            {% render_field field class="form-control" %}
            {% for error in field.errors %}
              <span class="text-muted">{{ error }}</span>
            {% endfor %}
          </div>
        {% endfor %}

      </div>
      <div class="row">
        <button class='btn btn-primary mt-3' type="submit">Salvar</button>
      </div>
    </div>

  </form>
{% endblock content %}

{% block js %}
  <script src="{% static 'js/script.js' %}"></script>
{% endblock js %}

backend/crm/templates/crm/fornecedor_list.html
{% extends 'base.html'%}
{% load static %}

{% block content %}
  <div class="card">
    <div class="d-flex bd-highlight">
      <div class="card-body">


        <h4 class="card-title mb-3">
          Fornecedores
          <a href="{% url 'crm:fornecedor_create' %}">
            <button type="button" class="btn btn-link shadow-none">
              Cadastrar
            </button>
          </a>
          <div class="dropdown d-inline">
            <a class="dropdown-toggle text-muted me-3 mb-3 align-middle" href="#" data-bs-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              <button type="button" class="btn btn-link shadow-none">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                  stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                  class="feather feather-search icon-sm">
                  <circle cx="11" cy="11" r="8"></circle>
                  <line x1="21" y1="21" x2="16.65" y2="16.65"></line>
                </svg><span>Buscar</span>
              </button></a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-end p-0">
              <form class="p-2">
                <div class="search-box">
                  <div class="position-relative">
                    <input type="text" class="form-control rounded bg-light border-0" placeholder="Buscar...">
                    <i class="font-size-16 search-icon"></i>

                  </div>
                </div>
              </form>
            </div>

          </div>
        </h4>

        <div class="table-responsive">
          <table class="table table-hover mb-0 align-middle">
            <thead class="bg-light">
              <tr>
                <th class="rounded-start" style="width: 15px;">
                  <div class="form-check">
                    <input class="form-check-input font-size-16" type="checkbox" value="" id="flexCheckDefault">
                    <label class="form-check-label" for="flexCheckDefault"> </label>
                  </div>
                </th>
                <th>Código</th>
                <th>Nome</th>
                <th>Razão Social</th>
                <th>Nome Fantasia</th>
                <th>Endereço</th>
                <th>Bairro</th>
                <th>Cidade</th>
                <th>Estado</th>
                <th>Ativo</th>
                <th></th>
              </tr>
              <!-- end tr -->
            </thead>
            <!-- end thead -->
            <tbody>
              {% for object in object_list %}
                <tr>
                  <td>
                    <div class="form-check">
                      <input class="form-check-input font-size-16" type="checkbox" value="" id="flexCheckexampleone">
                      <label class="form-check-label" for="flexCheckexampleone">
                      </label>
                    </div>
                  </td>
                  <td class="fw-medium">
                    {{ object.codigo }}
                  </td>
                  <td>
                    <a href="{{ object.get_absolute_url }}">{{ object.nome }}</a>
                  </td>
                  <td>
                    <div class="d-flex align-items-center">
                      <!-- Imagem do produto -->
                      <!--


                                  <div class="me-2">
                                      <img src="assets/images/users/avatar-2.jpg" class="avatar-sm img-thumbnail h-auto rounded-circle" alt="Error">
                                  </div>
                                  -->

                      <div>
                        <h5 class="font-size-14 text-truncate mb-0">{{ object.razao_social }}
                        </h5>
                      </div>
                    </div>
                  </td>
                  <td>
                    {{ object.nome_fantasia }}
                  </td>

                  <td>
                    {{ object.address }}
                  </td>
                  <td>
                    {{ object.district }}
                  </td>
                  <td>
                    {{ object.city }}
                  </td>
                  <td>
                    {{ object.uf }}
                  </td>
                  <td>
                    <div class="d-flex">
                      <div class="me-2">
                        {% if object.active %}
                          <i class="mdi mdi-check-circle-outline text-success"></i>
                        {% else %}
                          <i class="mdi mdi-close-circle-outline text-danger"></i>
                        {% endif %}
                      </div>
                    </div>
                  </td>
                  <td style="min-width: 70px">
                    <span>
                      <a href="#"><i class="mdi mdi-pencil text-success me-1"></i></a>
                    </span>
                    <span>
                      <a href="#"><i class="mdi mdi-trash-can text-danger me-1"></i></a>
                    </span>
                  </td>
                </tr>
              {% endfor %}
              <!-- end /tr -->
            </tbody><!-- end tbody -->
          </table><!-- end table -->
        </div>
      </div>
    </div>
{% endblock content %}