backend/core/urls.py
from django.urls import path

from backend.core import views as v

app_name = 'core'

urlpatterns = [
    path('', v.index, name='index'),
]

backend/crm/urls.py
from django.urls import include, path

from backend.crm import views as v

app_name = 'crm'


cliente_urlpatterns = [
    path('', v.ClienteListView.as_view(), name='cliente_list'),  # noqa E501
    path('detail/<int:pk>/', v.ClienteDetailView.as_view(), name='cliente_detail'),  # noqa E501
    path('create/', v.ClienteCreateView.as_view(), name='cliente_create'),  # noqa E501
]


fornecedor_urlpatterns = [
    path('', v.FornecedorListView.as_view(), name='fornecedor_list'),  # noqa E501
    path('detail/<int:pk>/', v.FornecedorDetailView.as_view(), name='fornecedor_detail'),  # noqa E501
    path('create/', v.FornecedorCreateView.as_view(), name='fornecedor_create'),  # noqa E501
]


urlpatterns = [
    path('cliente/', include(cliente_urlpatterns)),
    path('fornecedor/', include(fornecedor_urlpatterns)),
]

backend/orcamento/urls.py
from django.urls import include, path

from backend.orcamento import views as v

app_name = 'orcamento'


orcamento_patterns = [
    path('', v.OrcamentoListView.as_view(), name='orcamento_list'),  # noqa E501
    path('detail/<int:pk>/', v.OrcamentoDetailView.as_view(), name='orcamento_detail'),  # noqa E501
    path('create/<int:client_pk>/', v.orcamento_create, name='orcamento_create'),  # noqa E501
    path('update/<int:pk>/', v.orcamento_update, name='orcamento_update'),  # noqa E501
    path('produto/preco/', v.produto_preco, name='produto_preco'),  # noqa E501
    path('search/', v.produto_items_search, name='produto_items_search'),  # noqa E501
    path('add-row/', v.add_row_orcamento_items_hx, name='add_row_orcamento_items_hx'),  # noqa E501
    path('invoice/<int:pk>/', v.orcamento_invoice, name='orcamento_invoice'),  # noqa E501
]

contrato_patterns = [
    path('create/<int:orcamento_pk>/', v.contrato_create, name='contrato_create'),  # noqa E501
    path('<int:pk>/', v.ContratoDetailView.as_view(), name='contrato_detail'),  # noqa E501
]

urlpatterns = [
    path('orcamento/', include(orcamento_patterns)),
    path('contrato/', include(contrato_patterns)),
]

backend/produto/urls.py
from django.urls import path

from backend.produto import views as v

app_name = 'produto'


urlpatterns = [
    path('', v.ProdutoListView.as_view(), name='produto_list'),  # noqa E501
    path('detail/<int:pk>/', v.ProdutoDetailView.as_view(), name='produto_detail'),  # noqa E501
    path('create/', v.produto_create, name='produto_create'),  # noqa E501
    path('add-row/', v.add_row_produto_items_hx, name='add_row_produto_items_hx'),  # noqa E501
    path('produto-search/', v.produto_items_search, name='produto_items_search'),  # noqa E501
]

backend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('backend.core.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('crm/', include('backend.crm.urls', namespace='crm')),
    path('produto/', include('backend.produto.urls', namespace='produto')),
    path('orcamento/', include('backend.orcamento.urls', namespace='orcamento')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/core/models.py
from django.contrib.auth.models import User
from django.db import models
from localflavor.br.br_states import STATE_CHOICES


class TimeStampedModel(models.Model):
    created = models.DateTimeField('criado em', auto_now_add=True)
    modified = models.DateTimeField('modificado em', auto_now=True)
    deleted = models.DateTimeField('deletado em', null=True, blank=True)

    class Meta:
        abstract = True


class CreatedBy(models.Model):
    created_by = models.ForeignKey(
        User,
        verbose_name='criado por',
        on_delete=models.SET_NULL,
        related_name='%(app_label)s_%(class)s_created_by',
        null=True,
        blank=True,
    )

    class Meta:
        abstract = True


class DeletedBy(models.Model):
    deleted_by = models.ForeignKey(
        User,
        verbose_name='deletado por',
        on_delete=models.SET_NULL,
        related_name='%(app_label)s_%(class)s_deleted_by',
        null=True,
        blank=True,
    )

    class Meta:
        abstract = True


class Address(models.Model):
    address = models.CharField(
        'endereço',
        max_length=100,
        null=True,
        blank=True
    )
    address_number = models.IntegerField('número', null=True, blank=True)
    complement = models.CharField(
        'complemento',
        max_length=100,
        null=True,
        blank=True
    )
    district = models.CharField(
        'bairro',
        max_length=100,
        null=True,
        blank=True
    )
    city = models.CharField('cidade', max_length=100, null=True, blank=True)
    uf = models.CharField(
        'UF',
        max_length=2,
        choices=STATE_CHOICES,
        null=True,
        blank=True
    )
    cep = models.CharField('CEP', max_length=9, null=True, blank=True)
    country = models.CharField(
        'país',
        max_length=50,
        default='Brasil',
        null=True,
        blank=True
    )

    class Meta:
        abstract = True


class Active(models.Model):
    active = models.BooleanField('ativo', default=True)
    exist_deleted = models.BooleanField(
        'existe/deletado',
        default=True,
        help_text='Se for True o item existe. Se for False o item foi deletado.'
    )

    class Meta:
        abstract = True

backend/core/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

# Create your views here.


@login_required
def index(request):
    template_name = 'index.html'
    context = {
    }
    return render(request, template_name, context)

backend/core/templates/includes/navbar.html
{% load static %}
<header id="page-topbar">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a href="index.html" class="logo logo-dark">
      <span class="logo-sm">
        <img src="{% static '/img/logo-sm.png' %}" alt="" height="22">
      </span>
      <span class="logo-lg">
        <img src="{% static '/img/logo-dark.png' %}" alt="" height="22">
      </span>
    </a>

    <a href="index.html" class="logo logo-light">
      <span class="logo-sm">
        <img src="{% static '/img/logo-sm.png' %}" alt="" height="22">
      </span>
      <span class="logo-lg">
        <img src="{% static '/img/logo-light.png' %}" alt="" height="22">
      </span>
    </a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle arrow-down" href="{% url 'orcamento:orcamento_list' %}" id="navbarDropdown">
            <i class="icon nav-icon" data-feather="grid"></i> Orçamentos
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle arrow-down" href="{% url 'produto:produto_list' %}" id="navbarDropdown">
            <i class="icon nav-icon" data-feather="grid"></i> Produto
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle arrow-down" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="icon nav-icon" data-feather="grid"></i> Financeiro
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle arrow-down" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="icon nav-icon" data-feather="package"></i> Estoque
          </a>
        </li>

        <!-- <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle arrow-none" href="#" id="topnav-more" role="button">
                <i class="icon nav-icon" data-feather="file"></i>
                <span data-key="t-extra-pages">Relatórios</span>
                <div class="arrow-down"></div>
              </a>
            </li> -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle arrow-down" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="icon nav-icon" data-feather="grid"></i> Cadastros
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Empresa</a></li>
            <li><a class="dropdown-item" href="{% url 'crm:cliente_list' %}">Clientes</a></li>
            <li><a class="dropdown-item" href="{% url 'crm:fornecedor_list' %}">Fornecedores</a></li>
            <li><a class="dropdown-item" href="#">Contas</a></li>
          </ul>
        </li>
      </ul>
      <div class="dropdown d-inline-block">
        <button type="button" class="btn header-item user text-start d-flex align-items-center"
          id="page-header-user-dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <img class="rounded-circle header-profile-user" src="{% static 'img/users/avatar-1.jpg' %}" alt="Header Avatar">
          <span class="ms-2 d-none d-sm-block user-item-desc">
            <span class="user-name">{{user.first_name}}</span>
            <span class="user-sub-title">{{user.email}}</span>
          </span>
        </button>
        <div class="dropdown-menu dropdown-menu-end pt-0">
          <div class="p-3 bg-primary border-bottom">
            <h6 class="mb-0 text-white">{{user.first_name}}</h6>
            <p class="mb-0 font-size-11 text-white-50 fw-semibold">{{user.email}}</p>
          </div>
          {% if request.user.is_authenticated %}
            <a class="dropdown-item" href="{% url 'logout' %}"><i
              class="mdi mdi-logout text-muted font-size-16 align-middle me-1"></i> <span
                class="align-middle">Sair</span></a>
          {% endif %}

        </div>
      </div>
    </div>

  </div>
</nav>
</header>