backend/orcamento/urls.py
from django.urls import include, path

from backend.orcamento import views as v

app_name = 'orcamento'


orcamento_patterns = [
    path('', v.OrcamentoListView.as_view(), name='orcamento_list'),  # noqa E501
    path('detail/<int:pk>/', v.OrcamentoDetailView.as_view(), name='orcamento_detail'),  # noqa E501
    path('create/<int:client_pk>/', v.orcamento_create, name='orcamento_create'),  # noqa E501
    path('update/<int:pk>/', v.orcamento_update, name='orcamento_update'),  # noqa E501
    path('produto/preco/', v.produto_preco, name='produto_preco'),  # noqa E501
    path('search/', v.produto_items_search, name='produto_items_search'),  # noqa E501
    path('add-row/', v.add_row_orcamento_items_hx, name='add_row_orcamento_items_hx'),  # noqa E501
    path('invoice/<int:pk>/', v.orcamento_invoice, name='orcamento_invoice'),  # noqa E501
]

contrato_patterns = [
    path('create/<int:orcamento_pk>/', v.contrato_create, name='contrato_create'),  # noqa E501
    path('<int:pk>/', v.ContratoDetailView.as_view(), name='contrato_detail'),  # noqa E501
]

urlpatterns = [
    path('orcamento/', include(orcamento_patterns)),
    path('contrato/', include(contrato_patterns)),
]

backend/orcamentos/urls.py
from django.urls import path

from backend.orcamentos import views as v

app_name = 'orcamentos'


urlpatterns = [
    path('create/<int:client_pk>', v.orcamento_create, name='orcamento_create'),
    path('list/', v.orcamento_list, name='orcamento_list'),
    path('search/', v.search, name='search'),
    path('add-row/<int:product_pk>', v.add_row_hx, name='add_row_hx'),
]

backend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('backend.core.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('crm/', include('backend.crm.urls', namespace='crm')),
    path('produto/', include('backend.produto.urls', namespace='produto')),
    path('orcamento/', include('backend.orcamento.urls', namespace='orcamento')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/orcamento/models.py
from datetime import timedelta

from django.db import models
from django.urls import reverse_lazy

from backend.core.models import Active, CreatedBy, DeletedBy, TimeStampedModel
from backend.crm.models import Cliente
from backend.produto.models import Patrimonio, Produto

STATUS_ORCAMENTO = (
    ('p', 'Pendente'),
    ('f', 'Finalizado'),
    ('c', 'Cancelado'),
)


class Orcamento(TimeStampedModel, CreatedBy, DeletedBy, Active):
    cliente = models.ForeignKey(
        Cliente,
        on_delete=models.SET_NULL,
        related_name='cliente_orcamentos',
        null=True,
        blank=True
    )
    periodo = models.PositiveSmallIntegerField('Período (em dias)', default=0)
    desconto = models.DecimalField(
        'Desconto (%)',
        max_digits=4,
        decimal_places=2,
        blank=True,
        null=True,
        help_text='Em porcentagem'
    )
    status = models.CharField(max_length=1, choices=STATUS_ORCAMENTO, default='p')  # noqa E501

    class Meta:
        ordering = ('-pk',)
        verbose_name = 'Orçamento'
        verbose_name_plural = 'Orçamentos'

    def __str__(self):
        return f'{str(self.pk).zfill(3)}'

    def get_absolute_url(self):
        return reverse_lazy('orcamento:orcamento_detail', kwargs={'pk': self.pk})

    def total(self):
        qs = self.orcamentos.filter(orcamento=self.pk).values_list(
            'valor', 'quantidade') or 0
        total = 0 if isinstance(qs, int) else sum(
            map(lambda q: q[0] * q[1], qs))
        return total


class OrcamentoItens(models.Model):
    orcamento = models.ForeignKey(
        Orcamento,
        on_delete=models.CASCADE,
        related_name='orcamentos',
    )
    produto = models.ForeignKey(
        Produto,
        on_delete=models.SET_NULL,
        related_name='produto_orcamentos',
        null=True,
        blank=True
    )
    patrimonio = models.ForeignKey(
        Patrimonio,
        on_delete=models.SET_NULL,
        related_name='patrimonio_orcamentos',
        null=True,
        blank=True
    )
    quantidade = models.PositiveSmallIntegerField('Quantidade', default=1)
    valor = models.DecimalField(
        'Valor',
        max_digits=8,
        decimal_places=2,
        blank=True,
        null=True
    )

    class Meta:
        ordering = ('pk',)
        verbose_name = 'Orçamento Item'
        verbose_name_plural = 'Orçamento Itens'

    def __str__(self):
        return f'{self.pk}'

    def subtotal(self):
        return self.valor * (self.quantidade or 0)


STATUS_CONTRATO = (
    ('p', 'Pendente'),
    ('f', 'Finalizado'),
    ('c', 'Cancelado'),
)


class Contrato(TimeStampedModel, CreatedBy, DeletedBy, Active):
    orcamento = models.OneToOneField(
        Orcamento,
        verbose_name='orçamento',
        related_name='contrato',
        on_delete=models.CASCADE
    )
    status = models.CharField(max_length=1, choices=STATUS_CONTRATO, default='p')  # noqa E501

    class Meta:
        ordering = ('-pk',)
        verbose_name = 'contrato'
        verbose_name_plural = 'contratos'

    @property
    def codigo(self):
        return str(self.pk).zfill(3)

    def __str__(self):
        return f'{self.codigo}'

    @property
    def data_final(self):
        return self.created + timedelta(self.orcamento.periodo)

    def get_absolute_url(self):
        return reverse_lazy('orcamento:contrato_detail', pk=self.pk)

backend/orcamentos/models.py
from django.db import models

from backend.clientes.models import Clientes
from backend.produtos.models import Patrimonio, Produtos


class Orcamentos(models.Model):

    cliente = models.ForeignKey(
        Clientes,
        on_delete=models.SET_NULL,
        related_name='cliente_orcamentos',
        null=True,
        blank=True
    )

    created_user = models.CharField(
        max_length=100,
        null=True,
        blank=True
    )

    delete_user = models.CharField(
        max_length=100,
        null=True,
        blank=True
    )

    checkbox = models.BooleanField(
        "Excluir",
        max_length=10
    )

    created_at = models.DateTimeField(
        auto_now_add=True
    )

    updated_at = models.DateTimeField(
        auto_now=True
    )

    delete_at = models.DateTimeField(
        null=True,
        blank=True
    )

    class Meta:
        ordering = ('created_at',)
        verbose_name = "Orçamento"
        verbose_name_plural = "Orçamentos"

    def __str__(self):
        return f'{self.pk}'


class OrcamentosItens(models.Model):
    orcamento = models.ForeignKey(
        Orcamentos,
        on_delete=models.CASCADE,
        related_name='orcamentos',
    )
    produto = models.ForeignKey(
        Produtos,
        on_delete=models.SET_NULL,
        related_name='produto_orcamentos',
        null=True,
        blank=True
    )
    patrimonio = models.ForeignKey(
        Patrimonio,
        on_delete=models.SET_NULL,
        related_name='patrimonio_orcamentos',
        null=True,
        blank=True
    )
    valor = models.DecimalField(
        'Valor',
        max_digits=6,
        decimal_places=2,
        blank=True,
        null=True
    )

    class Meta:
        ordering = ('-pk',)
        verbose_name = "Orçamento Item"
        verbose_name_plural = "Orçamento Itens"

    def __str__(self):
        return f'{self.pk}'

backend/orcamento/forms.py
from django import forms
from django.forms import inlineformset_factory

from .models import Orcamento, OrcamentoItens


class OrcamentoForm(forms.ModelForm):
    required_css_class = 'required'

    class Meta:
        model = Orcamento
        fields = ('cliente', 'periodo', 'desconto', 'status')

    def __init__(self, *args, **kwargs):
        super(OrcamentoForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field = self.fields.get(field_name)
            field.widget.attrs.update({'placeholder': field.label})
            field.widget.attrs['class'] = 'form-control'

        self.fields['cliente'].disabled = True


class OrcamentoItensForm(forms.ModelForm):
    id = forms.IntegerField()

    class Meta:
        model = OrcamentoItens
        fields = (
            'orcamento',
            'id',
            'produto',
            'patrimonio',
            'quantidade',
            'valor',
        )

    def __init__(self, *args, **kwargs):
        super(OrcamentoItensForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

        self.fields['orcamento'].label = ''
        self.fields['orcamento'].widget = forms.HiddenInput()

        self.fields['id'].label = ''
        self.fields['id'].widget = forms.HiddenInput()


OrcamentoItemsFormset = inlineformset_factory(
    Orcamento,
    OrcamentoItens,
    form=OrcamentoItensForm,
    extra=0,
    can_delete=False,
    min_num=1,
    validate_min=True,
)

backend/orcamento/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin as LRM
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, UpdateView

from backend.crm.models import Cliente
from backend.produto.models import Produto

from .forms import OrcamentoForm, OrcamentoItemsFormset, OrcamentoItensForm
from .models import Contrato, Orcamento


class OrcamentoListView(LRM, ListView):
    model = Orcamento


class OrcamentoDetailView(LRM, DetailView):
    model = Orcamento


@login_required
def orcamento_create(request, client_pk):
    cliente = Cliente.objects.get(pk=client_pk)
    orcamento = Orcamento.objects.create(cliente=cliente)
    return redirect(reverse_lazy('orcamento:orcamento_update', kwargs={'pk': orcamento.pk}))  # noqa E501


@login_required
def orcamento_update(request, pk):
    template_name = 'orcamento/orcamento_form.html'
    orcamento_instance = Orcamento.objects.get(pk=pk)

    if orcamento_instance.status == 'f':
        # Se orçamento estiver 'Finalizado'...
        messages.add_message(request, messages.ERROR, 'Não é permitido editar orçamento já finalizado.')  # noqa E501
        return redirect(reverse_lazy('orcamento:orcamento_list'))

    form = OrcamentoForm(request.POST or None, instance=orcamento_instance, prefix='main')  # noqa E501
    formset = OrcamentoItemsFormset(request.POST or None, instance=orcamento_instance, prefix='items')  # noqa E501

    if request.method == 'POST':
        if form.is_valid() and formset.is_valid():
            form.save()
            formset.save()
            return redirect('orcamento:orcamento_list')

    context = {
        'form': form,
        'formset': formset,
        'orcamento': orcamento_instance
    }
    return render(request, template_name, context)


@login_required
def add_row_orcamento_items_hx(request):
    template_name = 'orcamento/hx/row_orcamento_items_hx.html'
    form = OrcamentoItensForm()
    context = {'orcamento_item_form': form}
    return render(request, template_name, context)


@login_required
def produto_preco(request):
    template_name = 'orcamento/hx/produto_preco_hx.html'
    url = request.get_full_path()
    item = url.split('-')[1]
    produto_pk = list(request.GET.values())[0]
    produto = Produto.objects.get(pk=produto_pk)

    context = {'produto': produto, 'item': item[0]}
    return render(request, template_name, context)


@login_required
def produto_items_search(request):
    template = 'orcamento/hx/orcamento_results_search.html'
    search_text = request.GET.get('search')
    results = Produto.objects.filter(titulo__icontains=search_text)
    context = {'results': results}
    return render(request, template, context)


@login_required
def orcamento_invoice(request, pk):
    template = 'orcamento/orcamento_invoice.html'
    return render(request, template)


@login_required
def contrato_create(request, orcamento_pk):
    orcamento = get_object_or_404(Orcamento, pk=orcamento_pk)
    contrato, _ = Contrato.objects.get_or_create(orcamento=orcamento)
    return redirect(reverse_lazy('orcamento:contrato_detail', kwargs={'pk': contrato.pk}))  # noqa E501


class ContratoDetailView(LRM, DetailView):
    template_name = 'contrato/contrato_detail.html'
    model = Contrato


@login_required
def clear(request):
    return HttpResponse('')

backend/orcamentos/views.py
from itertools import product

from django.contrib import messages
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render

from backend.clientes.models import Clientes
from backend.produtos.forms import *
from backend.produtos.models import Patrimonio, Produtos

from .forms import OrcamentosForm, OrcamentosFormSet
from .models import Orcamentos, OrcamentosItens

# Create your views here.


def orcamento_list(request):
    template_name = 'orcamento_list.html'
    objects = Orcamentos.objects.all()
    context = {
        'object_list': objects,
    }
    return render(request, template_name, context)


def orcamento_create(request, client_pk):
    template_name = 'orcamento_form_add.html'
    name = request.GET.get("searchField")

    if name == None:
        name = ''
        cliente = Clientes.objects.filter(nome__icontains=name)
        cliente = Clientes.objects.get(pk=client_pk)
    else:
        # add film
        cliente = Clientes.objects.filter(nome__icontains=name)
        context = {
            'object_list': cliente,
            'title': 'Cadastro Orçamentos',
        }
        return render(request, template_name, context)
    # add the film to the user's list
    # request.user.filclientems.add(cliente)

    # return template fragment with all the user's films
    context = {
        'object_list': cliente,
        'title': 'Cadastro Orçamentos',
    }
    return render(request, template_name, context)


def add_orcamento(request, client_pk):
    template_name = 'orcamento_form_add.html'
    cliente = Clientes.objects.get(pk=client_pk)
    context = {'object_list': cliente}
    return render(request, template_name, context)


def search(request):
    template = 'orcamento_results_search.html'
    search_text = request.GET.get('search')
    results = Produtos.objects.filter(nome__icontains=search_text)

    context = {"results": results}
    return render(request, template, context)


def clear(request):
    return HttpResponse("")


def add_row_hx(request, product_pk):
    template = 'orcamento_list.html'
    produto = Produtos.objects.get(pk=product_pk)
    form = OrcamentosFormSet()

    context = {
        'form': form,
        'object_list_product': produto,
    }
    return render(request, template, context)


def order_update(request, product_pk):
    template_name = 'orcamento_form_add.html'
    obj = Produtos.objects.get(pk=product_pk)
    form = OrcamentosForm(isinstance=obj)
    context = {'form': form}
    return render(request, template_name, context)


def post_update(request, id):
    product = get_object_or_404(Produtos, pk=id)
    form = Produtos(instance=product)
    if(request.method == 'POST'):
        form = Produtos(request.POST, instance=product)

        if(form.is_valid()):
            post = form.save(commit=False)
            post.title = form.cleaned_data['title']
            post.description = form.cleaned_data['slug']
            post.body = form.cleaned_data['body']
            post.author = form.cleaned_data['author']
            post.status = form.cleaned_data['status']
            post.save()
            return redirect('blog:post_list')
        else:
            return render(request, 'blog/edit_post.html', {'form': form, 'post': post})
    elif(request.method == 'GET'):
        return render(request, 'blog/edit_post.html', {'form': form, 'post': post})

backend/orcamentos/templates/formOrcamentos.html
{% extends 'base.html'%}
{% load static %}

{% block cadClient %}

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4 mt-1">
        <h2>{{title}}</h2>
        <div class="container-fluid ">
            <div class="py-5 text-center mt-1">
                <img class="d-block mx-auto mb-1" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt=""
                    width="72" height="72">
                <h4>{{object_list.id}} - {{object_list.nome}}</h4>
            </div>
            <div class="container col-md-10">
                <legend>Buscar Produtos</legend>
                <input class="form-control" type="search" name="search" placeholder="Digite o produto..."
                    hx-get="{% url 'orcamentos:search' %}" hx-trigger="keyup changed delay:250ms, search"
                    hx-target="#search-results">
                <span id="search-results"></span>
            </div>
            <!--

  
  -->
            <div class="col-md mt-lg-4">
                <h4 class="d-flex justify-content-between align-items-center mb-1">
                    <span class="text-muted">Produtos Cotados</span>
                    <span class="badge badge-secondary badge-pill">{}</span>
                </h4>
                <div class="table-responsive mt-lg-3">
                    <form action = "" method = "post">
                        {% csrf_token %}
                        <table class="table table-striped table-sm">
                            <thead>
                                <tr>
                                    <th>Código</th>
                                    <th>Tipo</th>
                                    <th>Nome</th>
                                    <th>Quantidade</th>
                                    <th>Valor locação</th>
                                </tr>
                            </thead>
                            {% include "listarOrcamen.html" %}

                        </table>
                    </form>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

backend/orcamentos/templates/listarOrcamen.html
<tbody id="table-list">
    <tr></tr>
    <td>{{object_list_product.codigo}}</td>
    <td>{{object_list_product.nome}}</td>
    <td>{{object_list_product.id_grupo}}</td>
    <td>{{object_list_product.nome}}</td>
    <td>{{object_list_product.valor_Locacao}}</td>
</tr>
</tbody>

backend/orcamentos/templates/orcamento_form_add.html
{% extends 'base.html'%}
{% load static %}
{% block orcamentos_form %}


  <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4 mt-1">
    <h5>{{title}}</h5>
    <div class="container-fluid ">
      <div class="py-5 text-center mt-1">
        <img class="d-block mx-auto mb-1" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt=""
          width="72" height="72">
        <h6>{{object_list.id}} - {{object_list.nome}}</h6>
      </div>
      <div class="container col-md-10">
        <legend>Buscar Produtos</legend>
        <input class="form-control" type="search" name="search" placeholder="Digite o produto..."
          hx-get="{% url 'orcamentos:search' %}" hx-trigger="keyup changed delay:250ms, search"
          hx-target="#search-results">
        <span id="search-results"></span>
      </div>
      {% include 'orcamento_table.html'%}
    </div>
  </main>
{% endblock orcamentos_form %}

backend/orcamentos/templates/orcamento_results_search.html
{% if results %}
  {% csrf_token %}
  <ul class="list-group col-xs-12">
    {% for result in results %}
      <li class="list-group-item d-flex justify-content-between align-items-center">
        {{ result.nome }}
        <span class="badge badge-success badge-pill"
          style="cursor: pointer;"
          hx-trigger="click"
          hx-post="{% url 'orcamentos:add_row_hx' result.id %}"
          hx-swap= "beforebegin"
          hx-vals='{"resultname": "{{result.nome}}"'
          hx-target="#table-list">Adicionar
        </span>
      </li>
    {% endfor %}

  </ul>
{% else %}
  <p>Não foi encontrado nada </p>
{% endif %}